name: terraform-multi-env-10

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment"
        required: true
        type: choice
        options:
          - dev
          - qa
          - prod

      base_bucket_name:
        description: "Enter Base Bucket Name (e.g. abc)"
        required: true

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Environment Variable
        run: echo "ENVIRONMENT=${{ github.event.inputs.environment }}" >> $GITHUB_ENV

      - name: Set AWS Region
        run: |
          if [[ "${{ github.event.inputs.environment }}" == "dev" ]]; then
            echo "AWS_REGION=ap-south-1" >> $GITHUB_ENV
          elif [[ "${{ github.event.inputs.environment }}" == "qa" ]]; then
            echo "AWS_REGION=us-east-1" >> $GITHUB_ENV
          elif [[ "${{ github.event.inputs.environment }}" == "prod" ]]; then
            echo "AWS_REGION=eu-west-1" >> $GITHUB_ENV
          fi

      - name: Generate Bucket Name
        run: |
          FINAL_NAME="${{ github.event.inputs.base_bucket_name }}-${{ github.event.inputs.environment }}"
          echo "BUCKET_NAME=$FINAL_NAME" >> $GITHUB_ENV

      # (Optional) Validate bucket name
      - name: Validate Bucket Name
        run: |
          if [[ ! "${{ env.BUCKET_NAME }}" =~ ^[a-z0-9.-]+$ ]]; then
            echo "Invalid bucket name format"
            exit 1
          fi

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_ID }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        working-directory: environments/${{ env.ENVIRONMENT }}
        run: terraform init

      - name: Terraform Plan
        working-directory: environments/${{ env.ENVIRONMENT }}
        run: |
          terraform plan \
          -var="aws_region=${{ env.AWS_REGION }}" \
          -var="environment=${{ env.ENVIRONMENT }}" \
          -var="bucket_name=${{ env.BUCKET_NAME }}"

      - name: Terraform Apply
        working-directory: environments/${{ env.ENVIRONMENT }}
        run: |
          terraform apply -auto-approve \
          -var="aws_region=${{ env.AWS_REGION }}" \
          -var="environment=${{ env.ENVIRONMENT }}" \
          -var="bucket_name=${{ env.BUCKET_NAME }}"
