name: terraform-s3-deploy

on:
  push:
    branches: [dev, qa, main]
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment"
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Environment
        run: |
          if [ "${{ github.event.inputs.environment }}" != "" ]; then
            echo "ENV=${{ github.event.inputs.environment }}" >> $GITHUB_ENV
          else
            if [[ "${GITHUB_REF}" == "refs/heads/dev" ]]; then echo "ENV=dev" >> $GITHUB_ENV; fi
            if [[ "${GITHUB_REF}" == "refs/heads/qa" ]]; then echo "ENV=qa" >> $GITHUB_ENV; fi
            if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then echo "ENV=prod" >> $GITHUB_ENV; fi
          fi

      - name: Set AWS Region
        run: |
          if [ "$ENV" == "dev" ]; then echo "AWS_REGION=ap-south-1" >> $GITHUB_ENV; fi
          if [ "$ENV" == "qa" ]; then echo "AWS_REGION=us-east-1" >> $GITHUB_ENV; fi
          if [ "$ENV" == "prod" ]; then echo "AWS_REGION=eu-west-1" >> $GITHUB_ENV; fi

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_REGION: ${{ env.AWS_REGION }}
        run: terraform init
        working-directory: environments/${{ env.ENV }}

      - name: Terraform Apply
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_REGION: ${{ env.AWS_REGION }}
        run: terraform apply -auto-approve
        working-directory: environments/${{ env.ENV }}
